version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - WANDB_API_KEY=<key>
      - MODEL_NAME=<name>
      - VERSION=<version>
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=<url>
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped


networks:
  default:
    driver: bridge
