name: Trigger auto deployment for frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/frontend-AutoDeployTrigger-0e9d4371-792d-4cde-b81e-e41463bafe78.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.FRONTEND_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/frontend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: sentimentdemomoiz.azurecr.io
          registryUsername: ${{ secrets.FRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRONTEND_REGISTRY_PASSWORD }}
          containerAppName: frontend
          resourceGroup: moeezsession
          imageToBuild: sentimentdemomoiz.azurecr.io/frontend:${{ github.sha }}
          
            

     

