name: Trigger auto deployment for frontend-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/frontend-app-AutoDeployTrigger-50339a57-a96c-4611-9807-fe5b11ad35a1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FRONTENDAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FRONTENDAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FRONTENDAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/frontend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: appfrontend.azurecr.io
          registryUsername: ${{ secrets.FRONTENDAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRONTENDAPP_REGISTRY_PASSWORD }}
          containerAppName: frontend-app
          resourceGroup: model-inference-app
          imageToBuild: appfrontend.azurecr.io/frontend-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


